spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          user_jdbc_metadata_defaults: false
    open-in-view: false

  # sharding-jdbc配置
  shardingsphere:
    # 输出SQL日志
    props:
      sql:
        show: true
    datasource:
      # 数据源名称
      names: db1, db2
      # 配置数据源
      db1:
        # 第三方数据库连接池 - druid
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/sharding_db_1
        username: sharding
        password: sharding
      db2:
        # 第三方数据库连接池 - druid
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/sharding_db_2
        username: sharding
        password: sharding
    # 数据分片
    sharding:
      # 配置需要分表操作的表名
      tables:
        # 逻辑表名
        sjd_enterprise:
          # groovy表达式，配置数据节点，sjd_enterprise_1/sjd_enterprise_2
          actual-data-nodes: db$->{1..2}.sjd_enterprise
          # 分库策略，enterprise为偶数操作db1，为奇数操作db2
          database-strategy:
            inline:
              sharding-column: enterprise_id
              algorithm-expression: db$->{enterprise_id % 2 + 1}
        # 逻辑表名
        sjd_user:
          # groovy表达式，配置数据节点，db1或者db2
          actual-data-nodes: db$->{1..2}.sjd_user
          # 分库策略
          database-strategy:
            inline:
              # 指定表的分片策略：分片键
              sharding-column: user_id
              # 指定表的分片策略：分片算法
              algorithm-expression: db$->{user_id % 2 + 1}