spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false

  # sharding-jdbc配置
  shardingsphere:
    # 输出SQL日志
    props:
      sql:
        show: true
    datasource:
      # 数据源名称
      names: db1
      # 配置数据源
      db1:
        # 第三方数据库连接池 - druid
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/sharding_db_1
        username: sharding
        password: sharding
    sharding:
      # 配置需要分表操作的表名
      tables:
        # 逻辑表名
        sjd_enterprise:
          # groovy表达式，配置数据节点，sjd_enterprise_1/sjd_enterprise_2
          actual-data-nodes: db1.sjd_enterprise_$->{1..2}
          # 分表策略，enterprise_code，获取首字母byte序列取模
          table-strategy:
            inline:
              # 指定表的分片策略：分片键
              sharding-column: enterprise_id
              # 指定表的分片策略：自定义分片算法
              algorithm-expression: sjd_enterprise_$->{enterprise_id % 2 + 1}
        # 逻辑表名
        sjd_user:
          # groovy表达式，配置数据节点，db1或者db2
          actual-data-nodes: db1.sjd_user_$->{1..2}
          # 分表策略
          table-strategy:
            inline:
              # 指定表的分片策略：分片键
              sharding-column: user_id
              # 指定表的分片策略：分片算法
              algorithm-expression: sjd_user_$->{user_id % 2 + 1}